menu:
  Blog: /
  Archive: /archives/
  Tags: /tags/
  About: /about/
  GitHub: https://github.com/dasoncheng

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
utterances:
  src: https://utteranc.es/client.js
  repo: dasoncheng/myour.cc
  issue_term: title
  theme: github-light
# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x
baidu:
  analytics: https://hm.baidu.com/hm.js?67cdd0b70a5050a16a58fc3901e5709a
# Copyright Infomation
startyear: 2015
