name: Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: git config
        run: |
          git config --global user.name ${{secrets.name}}
          git config --global user.email ${{secrets.email}}
          git remote set-url origin https://x-access-token:${{ secrets.github_token }}@github.com/myour.cc.git
      - name: npm install, build, and deploy
        run: |
          npm install
          npm run build
          npm run deploy
